#ifndef CACHEHOUND_CACHEHOUND_HPP
#define CACHEHOUND_CACHEHOUND_HPP

#include "./adapters/armv8_bypass_adapter.hpp"
#include "./adapters/bypass_adapter.hpp"
#include "./adapters/physical_adapter.hpp"

#include "./algo/find_eviction_set.hpp"
#include "./algo/is_eviction_set.hpp"
#include "./algo/locate_eviction_set.hpp"
#include "./algo/measure_sequence.hpp"
#include "./algo/minimize_eviction_set.hpp"
#include "./algo/reduce_eviction_set.hpp"
#include "./algo/simulate_sequence.hpp"

#include "./backends/kernel_memory.hpp"

#include "./concepts/address_distribution.hpp"
#include "./concepts/address_range.hpp"
#include "./concepts/armv8_memory.hpp"
#include "./concepts/eviction_strategy.hpp"
#include "./concepts/extended_memory_region.hpp"
#include "./concepts/extended_memory_region_range.hpp"
#include "./concepts/flushable_memory.hpp"
#include "./concepts/instrumented_memory.hpp"
#include "./concepts/memory.hpp"
#include "./concepts/memory_region.hpp"
#include "./concepts/memory_region_range.hpp"
#include "./concepts/physically_indexable_memory.hpp"
#include "./concepts/placement_policy.hpp"
#include "./concepts/replacement_policy.hpp"
#include "./concepts/resettable_memory.hpp"
#include "./concepts/sequence.hpp"
#include "./concepts/stats_memory.hpp"
#include "./concepts/switch_channel_memory.hpp"
#include "./concepts/timed_memory.hpp"
#include "./concepts/x86_memory.hpp"

#include "./policies/placement/affine_placement_policy.hpp"
#include "./policies/placement/generic_placement_policy.hpp"
#include "./policies/placement/modular_placement_policy.hpp"

#include "./policies/replacement/fifo_replacement_policy.hpp"
#include "./policies/replacement/linear_init_replacement_policy.hpp"
#include "./policies/replacement/lru_plru_replacement_policy.hpp"
#include "./policies/replacement/lru_replacement_policy.hpp"
#include "./policies/replacement/lru_wrapped_replacement_policy.hpp"
#include "./policies/replacement/mru_replacement_policy.hpp"
#include "./policies/replacement/plru_replacement_policy.hpp"
#include "./policies/replacement/qlru_replacement_policy.hpp"
#include "./policies/replacement/srrip_replacement_policy.hpp"

#include "./strategies/cisw_eviction_strategy.hpp"
#include "./strategies/eviction_set_strategy.hpp"

#include "./util/address_checker.hpp"
#include "./util/any_placement_policy.hpp"
#include "./util/any_replacement_policy.hpp"
#include "./util/basic_extended_memory_region.hpp"
#include "./util/basic_memory_region.hpp"
#include "./util/blacklisted_address_distribution.hpp"
#include "./util/concatenated_address_distribution.hpp"
#include "./util/locate_set.hpp"
#include "./util/memory_size.hpp"
#include "./util/replacement_policy.hpp"
#include "./util/sequence.hpp"
#include "./util/set_cycling_address_distribution.hpp"
#include "./util/uniform_address_distribution.hpp"
#include "./util/warmup.hpp"

#endif /* CACHEHOUND_CACHEHOUND_HPP */
